'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace wsASNOracle
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="BasicHttpBinding_IAsnService", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class AsnService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private GetAvailableAsnsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SaveAsnsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetPrepacksOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GenerateAsnReportOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.waSateliteWMS.My.MySettings.Default.waSateliteWMS_wsASNOracle_AsnService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event GetAvailableAsnsCompleted As GetAvailableAsnsCompletedEventHandler
        
        '''<remarks/>
        Public Event SaveAsnsCompleted As SaveAsnsCompletedEventHandler
        
        '''<remarks/>
        Public Event GetPrepacksCompleted As GetPrepacksCompletedEventHandler
        
        '''<remarks/>
        Public Event GenerateAsnReportCompleted As GenerateAsnReportCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IAsnService/GetAvailableAsns", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetAvailableAsns(ByVal initalDate As Date, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal initalDateSpecified As Boolean, ByVal endDate As Date, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal endDateSpecified As Boolean) As <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true), System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/STF.Asn.Entity.Data")> Asn()
            Dim results() As Object = Me.Invoke("GetAvailableAsns", New Object() {initalDate, initalDateSpecified, endDate, endDateSpecified})
            Return CType(results(0),Asn())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetAvailableAsnsAsync(ByVal initalDate As Date, ByVal initalDateSpecified As Boolean, ByVal endDate As Date, ByVal endDateSpecified As Boolean)
            Me.GetAvailableAsnsAsync(initalDate, initalDateSpecified, endDate, endDateSpecified, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetAvailableAsnsAsync(ByVal initalDate As Date, ByVal initalDateSpecified As Boolean, ByVal endDate As Date, ByVal endDateSpecified As Boolean, ByVal userState As Object)
            If (Me.GetAvailableAsnsOperationCompleted Is Nothing) Then
                Me.GetAvailableAsnsOperationCompleted = AddressOf Me.OnGetAvailableAsnsOperationCompleted
            End If
            Me.InvokeAsync("GetAvailableAsns", New Object() {initalDate, initalDateSpecified, endDate, endDateSpecified}, Me.GetAvailableAsnsOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetAvailableAsnsOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetAvailableAsnsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetAvailableAsnsCompleted(Me, New GetAvailableAsnsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IAsnService/SaveAsns", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SaveAsns(<System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true), System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/STF.Asn.Entity.Data")> ByVal asnCollection() As Asn) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> Transaction
            Dim results() As Object = Me.Invoke("SaveAsns", New Object() {asnCollection})
            Return CType(results(0),Transaction)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SaveAsnsAsync(ByVal asnCollection() As Asn)
            Me.SaveAsnsAsync(asnCollection, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SaveAsnsAsync(ByVal asnCollection() As Asn, ByVal userState As Object)
            If (Me.SaveAsnsOperationCompleted Is Nothing) Then
                Me.SaveAsnsOperationCompleted = AddressOf Me.OnSaveAsnsOperationCompleted
            End If
            Me.InvokeAsync("SaveAsns", New Object() {asnCollection}, Me.SaveAsnsOperationCompleted, userState)
        End Sub
        
        Private Sub OnSaveAsnsOperationCompleted(ByVal arg As Object)
            If (Not (Me.SaveAsnsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SaveAsnsCompleted(Me, New SaveAsnsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IAsnService/GetPrepacks", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetPrepacks(ByVal creationDate As Date, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal creationDateSpecified As Boolean) As <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true), System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/STF.Asn.Entity.Data")> Prepack()
            Dim results() As Object = Me.Invoke("GetPrepacks", New Object() {creationDate, creationDateSpecified})
            Return CType(results(0),Prepack())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetPrepacksAsync(ByVal creationDate As Date, ByVal creationDateSpecified As Boolean)
            Me.GetPrepacksAsync(creationDate, creationDateSpecified, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetPrepacksAsync(ByVal creationDate As Date, ByVal creationDateSpecified As Boolean, ByVal userState As Object)
            If (Me.GetPrepacksOperationCompleted Is Nothing) Then
                Me.GetPrepacksOperationCompleted = AddressOf Me.OnGetPrepacksOperationCompleted
            End If
            Me.InvokeAsync("GetPrepacks", New Object() {creationDate, creationDateSpecified}, Me.GetPrepacksOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetPrepacksOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetPrepacksCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetPrepacksCompleted(Me, New GetPrepacksCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IAsnService/GenerateAsnReport", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GenerateAsnReport(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal reportName As String, ByVal asnId As Integer, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal asnIdSpecified As Boolean) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> AsnReport
            Dim results() As Object = Me.Invoke("GenerateAsnReport", New Object() {reportName, asnId, asnIdSpecified})
            Return CType(results(0),AsnReport)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GenerateAsnReportAsync(ByVal reportName As String, ByVal asnId As Integer, ByVal asnIdSpecified As Boolean)
            Me.GenerateAsnReportAsync(reportName, asnId, asnIdSpecified, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GenerateAsnReportAsync(ByVal reportName As String, ByVal asnId As Integer, ByVal asnIdSpecified As Boolean, ByVal userState As Object)
            If (Me.GenerateAsnReportOperationCompleted Is Nothing) Then
                Me.GenerateAsnReportOperationCompleted = AddressOf Me.OnGenerateAsnReportOperationCompleted
            End If
            Me.InvokeAsync("GenerateAsnReport", New Object() {reportName, asnId, asnIdSpecified}, Me.GenerateAsnReportOperationCompleted, userState)
        End Sub
        
        Private Sub OnGenerateAsnReportOperationCompleted(ByVal arg As Object)
            If (Not (Me.GenerateAsnReportCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GenerateAsnReportCompleted(Me, New GenerateAsnReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/STF.Asn.Entity.Data")>  _
    Partial Public Class Asn
        
        Private dateField As Date
        
        Private dateFieldSpecified As Boolean
        
        Private destinyField As String
        
        Private documentField As String
        
        Private idField As Integer
        
        Private idFieldSpecified As Boolean
        
        Private itemsField() As AsnDetail
        
        Private numberField As String
        
        Private originField As String
        
        Private prefixField As String
        
        Private typeField As String
        
        Private userField As String
        
        '''<remarks/>
        Public Property [Date]() As Date
            Get
                Return Me.dateField
            End Get
            Set
                Me.dateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property DateSpecified() As Boolean
            Get
                Return Me.dateFieldSpecified
            End Get
            Set
                Me.dateFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Destiny() As String
            Get
                Return Me.destinyField
            End Get
            Set
                Me.destinyField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Document() As String
            Get
                Return Me.documentField
            End Get
            Set
                Me.documentField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Id() As Integer
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property IdSpecified() As Boolean
            Get
                Return Me.idFieldSpecified
            End Get
            Set
                Me.idFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true)>  _
        Public Property Items() As AsnDetail()
            Get
                Return Me.itemsField
            End Get
            Set
                Me.itemsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Number() As String
            Get
                Return Me.numberField
            End Get
            Set
                Me.numberField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Origin() As String
            Get
                Return Me.originField
            End Get
            Set
                Me.originField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Prefix() As String
            Get
                Return Me.prefixField
            End Get
            Set
                Me.prefixField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Type() As String
            Get
                Return Me.typeField
            End Get
            Set
                Me.typeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property User() As String
            Get
                Return Me.userField
            End Get
            Set
                Me.userField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/STF.Asn.Entity.Data")>  _
    Partial Public Class AsnDetail
        
        Private barCodeField As String
        
        Private colorField As String
        
        Private idField As Integer
        
        Private idFieldSpecified As Boolean
        
        Private lpnNumberField As String
        
        Private priceField As Decimal
        
        Private priceFieldSpecified As Boolean
        
        Private productTypeField As String
        
        Private quantityField As Decimal
        
        Private quantityFieldSpecified As Boolean
        
        Private referenceField As String
        
        Private sizeField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property BarCode() As String
            Get
                Return Me.barCodeField
            End Get
            Set
                Me.barCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Color() As String
            Get
                Return Me.colorField
            End Get
            Set
                Me.colorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Id() As Integer
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property IdSpecified() As Boolean
            Get
                Return Me.idFieldSpecified
            End Get
            Set
                Me.idFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property LpnNumber() As String
            Get
                Return Me.lpnNumberField
            End Get
            Set
                Me.lpnNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Price() As Decimal
            Get
                Return Me.priceField
            End Get
            Set
                Me.priceField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property PriceSpecified() As Boolean
            Get
                Return Me.priceFieldSpecified
            End Get
            Set
                Me.priceFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ProductType() As String
            Get
                Return Me.productTypeField
            End Get
            Set
                Me.productTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Quantity() As Decimal
            Get
                Return Me.quantityField
            End Get
            Set
                Me.quantityField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property QuantitySpecified() As Boolean
            Get
                Return Me.quantityFieldSpecified
            End Get
            Set
                Me.quantityFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Reference() As String
            Get
                Return Me.referenceField
            End Get
            Set
                Me.referenceField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Size() As String
            Get
                Return Me.sizeField
            End Get
            Set
                Me.sizeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/STF.Asn.Entity.Report")>  _
    Partial Public Class AsnReport
        
        Private customMessageField As String
        
        Private isSuccessfulField As Boolean
        
        Private isSuccessfulFieldSpecified As Boolean
        
        Private localPathField As String
        
        Private urlField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property CustomMessage() As String
            Get
                Return Me.customMessageField
            End Get
            Set
                Me.customMessageField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IsSuccessful() As Boolean
            Get
                Return Me.isSuccessfulField
            End Get
            Set
                Me.isSuccessfulField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property IsSuccessfulSpecified() As Boolean
            Get
                Return Me.isSuccessfulFieldSpecified
            End Get
            Set
                Me.isSuccessfulFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property LocalPath() As String
            Get
                Return Me.localPathField
            End Get
            Set
                Me.localPathField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Url() As String
            Get
                Return Me.urlField
            End Get
            Set
                Me.urlField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/STF.Asn.Entity.Data")>  _
    Partial Public Class PrepackDetail
        
        Private codeField As String
        
        Private colorField As String
        
        Private quantityField As Integer
        
        Private quantityFieldSpecified As Boolean
        
        Private referenceField As String
        
        Private sizeField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Code() As String
            Get
                Return Me.codeField
            End Get
            Set
                Me.codeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Color() As String
            Get
                Return Me.colorField
            End Get
            Set
                Me.colorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Quantity() As Integer
            Get
                Return Me.quantityField
            End Get
            Set
                Me.quantityField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property QuantitySpecified() As Boolean
            Get
                Return Me.quantityFieldSpecified
            End Get
            Set
                Me.quantityFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Reference() As String
            Get
                Return Me.referenceField
            End Get
            Set
                Me.referenceField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Size() As String
            Get
                Return Me.sizeField
            End Get
            Set
                Me.sizeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/STF.Asn.Entity.Data")>  _
    Partial Public Class Prepack
        
        Private codeField As String
        
        Private prepackDetailField() As PrepackDetail
        
        Private referenceField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Code() As String
            Get
                Return Me.codeField
            End Get
            Set
                Me.codeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true)>  _
        Public Property PrepackDetail() As PrepackDetail()
            Get
                Return Me.prepackDetailField
            End Get
            Set
                Me.prepackDetailField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Reference() As String
            Get
                Return Me.referenceField
            End Get
            Set
                Me.referenceField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/STF.Asn.Entity.Data")>  _
    Partial Public Class Transaction
        
        Private isSuccessfulField As Boolean
        
        Private isSuccessfulFieldSpecified As Boolean
        
        Private messageField As String
        
        '''<remarks/>
        Public Property IsSuccessful() As Boolean
            Get
                Return Me.isSuccessfulField
            End Get
            Set
                Me.isSuccessfulField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property IsSuccessfulSpecified() As Boolean
            Get
                Return Me.isSuccessfulFieldSpecified
            End Get
            Set
                Me.isSuccessfulFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Message() As String
            Get
                Return Me.messageField
            End Get
            Set
                Me.messageField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")>  _
    Public Delegate Sub GetAvailableAsnsCompletedEventHandler(ByVal sender As Object, ByVal e As GetAvailableAsnsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetAvailableAsnsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Asn()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Asn())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")>  _
    Public Delegate Sub SaveAsnsCompletedEventHandler(ByVal sender As Object, ByVal e As SaveAsnsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SaveAsnsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Transaction
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Transaction)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")>  _
    Public Delegate Sub GetPrepacksCompletedEventHandler(ByVal sender As Object, ByVal e As GetPrepacksCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetPrepacksCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Prepack()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Prepack())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")>  _
    Public Delegate Sub GenerateAsnReportCompletedEventHandler(ByVal sender As Object, ByVal e As GenerateAsnReportCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GenerateAsnReportCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As AsnReport
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),AsnReport)
            End Get
        End Property
    End Class
End Namespace
